# Generated by Django 5.1.6 on 2025-02-15 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('inventory', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
    ]
